INSERT INTO sectores VALUES ('PUROFM','001','1','Catedral',0.0);
INSERT INTO sectores VALUES ('PUROFM','001','2','San Blás',0.0);
INSERT INTO sectores VALUES ('PUROFM','001','3','San José',0.0);
INSERT INTO sectores VALUES ('PUROFM','001','4','Santa Rosa',0.0);
INSERT INTO sectores VALUES ('PUROFM','001','5','San Diego',0.0);
INSERT INTO sectores VALUES ('PUROFM','001','6','Naguanagua',0.0);
INSERT INTO sectores VALUES ('PUROFM','001','7','Catedral',0.0);
INSERT INTO sectores VALUES ('PUROFM','001','8','Agua Viva',0.0);
INSERT INTO sectores VALUES ('PUROFM','001','9','Capital Cabudare',0.0);
INSERT INTO sectores VALUES ('PUROFM','001','10','José Gregorio Bastidas',0.0);
INSERT INTO sectores VALUES ('PUROFM','001','11','Manuel Morillo',0.0);
INSERT INTO sectores VALUES ('PUROFM','001','12','Alfredo Pacheco Miranda',0.0);
INSERT INTO sectores VALUES ('PUROFM','001','13','Francisco de Miranda',0.0);
INSERT INTO sectores VALUES ('PUROFM','001','14','Francisco Linares Alcántara',0.0);
INSERT INTO sectores VALUES ('PUROFM','001','15','Mario Briceño Iragorry',0.0);
INSERT INTO sectores VALUES ('PUROFM','001','16','Monseñor Feliciano González',0.0);
INSERT INTO sectores VALUES ('PUROFM','001','17','Samán de Güere',0.0);
INSERT INTO sectores VALUES ('PUROFM','001','18','Urbana Andrés Eloy Blanco',0.0);
INSERT INTO sectores VALUES ('PUROFM','001','19','Urbana Joaquín Crespo',0.0);
INSERT INTO sectores VALUES ('PUROFM','001','20','Urbana José Casanova Godoy',0.0);
INSERT INTO sectores VALUES ('PUROFM','001','21','Urbana Los Tacariguas',0.0);
INSERT INTO sectores VALUES ('PUROFM','001','22','Urbana Pedro José Ovalles',0.0);
INSERT INTO sectores VALUES ('PUROFM','001','23','Altagracia',0.0);
INSERT INTO sectores VALUES ('PUROFM','001','24','La Pastora',0.0);
INSERT INTO sectores VALUES ('PUROFM','001','25','San José',0.0);
INSERT INTO sectores VALUES ('PUROFM','001','26','Catedral',0.0);
INSERT INTO sectores VALUES ('PUROFM','001','27','Santa Teresa',0.0);
INSERT INTO sectores VALUES ('PUROFM','001','28','El Valle',0.0);
INSERT INTO sectores VALUES ('PUROFM','001','29','El Paraíso',0.0);
