CREATE TABLE psk_pf.cliente (
	id_empresa varchar(6) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' NOT NULL,
	agencia varchar(3) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' NOT NULL,
	codigo varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NOT NULL,
	nombre char(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' NOT NULL,
	cedula varchar(14) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NOT NULL,
	nrorif varchar(25) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	nronit varchar(25) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	referenc1 varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	referenc2 varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	direccion varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	telefonos varchar(150) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	telefono_movil varchar(150) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	numerofax varchar(150) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	fecha date DEFAULT '0000-00-00' NOT NULL,
	perscont varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	limite double(20,7) DEFAULT 0.0000000 NOT NULL,
	dias double(5,0) DEFAULT 0 NOT NULL,
	precio double(2,0) DEFAULT 0 NOT NULL,
	status double(2,0) DEFAULT 0 NOT NULL,
	nota longtext CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
	credito varchar(1) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	sector varchar(6) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	formafis double(2,0) DEFAULT 0 NOT NULL,
	historia longtext CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
	email varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	wwwcli varchar(150) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	descuento double(20,7) DEFAULT 0.0000000 NOT NULL,
	vendedor varchar(8) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	motsuspend varchar(60) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	flotante double(4,0) DEFAULT 0 NOT NULL,
	tolerancia double(5,0) DEFAULT 0 NOT NULL,
	tipo varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	codigocont varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	direccobro longtext CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
	direcenvio longtext CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
	formaenvio varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	sexo double(2,0) DEFAULT 0 NOT NULL,
	nacionalidad varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	fechanac date DEFAULT '0000-00-00' NOT NULL,
	edocivil double(2,0) DEFAULT 0 NOT NULL,
	telhabitacion varchar(60) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	celular varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	anivbodas varchar(5) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	habcasa varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	habtorre varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	habpiso varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	habapto varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	habcalleav varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	haburb varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	trabempresa varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	trabcargo varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	trabcasaedif varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	trabtorre varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	trabpiso varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	traboficina varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	trabcalle varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	traburb varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	trabtelefono varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	parentesco1 varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	parentesco2 varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	parentesco3 varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	parentesco4 varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	parentesco5 varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	nomapell1 varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	nomapell2 varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	nomapell3 varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	nomapell4 varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	nomapell5 varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	fechanac1 date DEFAULT '0000-00-00' NOT NULL,
	fechanac2 date DEFAULT '0000-00-00' NOT NULL,
	fechanac3 date DEFAULT '0000-00-00' NOT NULL,
	fechanac4 date DEFAULT '0000-00-00' NOT NULL,
	fechanac5 date DEFAULT '0000-00-00' NOT NULL,
	profesion1 varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	profesion2 varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	profesion3 varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	profesion4 varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	profesion5 varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	diario varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	emisoraradio varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	mediovisto varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	sucursal varchar(15) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	contribespecial double(4,0) DEFAULT 0 NOT NULL,
	domiciliado double(4,0) DEFAULT 0 NOT NULL,
	excentomora double(4,0) DEFAULT 0 NOT NULL,
	moneda varchar(3) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	campo1 varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	campo2 varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	campo3 varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	campo4 varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	campo5 varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	codconvenio varchar(6) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	tipopersona double(4,0) DEFAULT 0 NOT NULL,
	codban_beneficiario varchar(3) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	codban_intermediario varchar(3) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	nombre_beneficiario varchar(60) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	cuenta_beneficiario varchar(60) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	tipo_cuenta_beneficiario varchar(25) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	codigo_swift_beneficiario varchar(25) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	codigo_iban_beneficiario varchar(25) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ' ' NULL,
	checapend double(2,0) DEFAULT 0 NOT NULL,
	noacepchk double(2,0) DEFAULT 0 NOT NULL,
	nota_cuenta_beneficiario longtext CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
	idtercero varchar(15) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' NULL,
	frog double(4,0) DEFAULT 0 NOT NULL,
	codpais varchar(3) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' NULL,
	masinfo text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
	tipoid double(2,0) DEFAULT 0 NOT NULL,
	regimen double(1,0) DEFAULT 0 NOT NULL,
	departamento varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' NOT NULL,
	subdivision varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' NOT NULL,
	ciudad varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' NOT NULL,
	subcodigo varchar(6) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' NOT NULL,
	hashtag longtext CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
	barrio varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' NOT NULL,
	esplantilla int(11) DEFAULT 0 NOT NULL,
	CONSTRAINT `PRIMARY` PRIMARY KEY (codigo,nombre,cedula),
	CONSTRAINT codigo UNIQUE KEY (codigo)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8
COLLATE=utf8_general_ci
COMMENT='innodb free: 7168 kb';
CREATE INDEX nombre USING BTREE ON psk_pf.cliente (nombre);
